### ISSUE TITLE
Enable more network modules in Kernel config

### ISSUE THREAD

**Issue by lotherk** [hexdump0815/linux-mainline-and-mali-generic-stable-kernel#5]
First of all, thank you for your work. I am so happy to be able to use my U3 again.

root@u3:/boot# uname -a
Linux u3 5.10.25-stb-exy+ #1 SMP PREEMPT Sun Mar 21 18:56:28 CET 2021 armv7l GNU/Linux

I'm trying to use it as a k3s master node, which sort of works but I have some troubles regarding iptables. I did not dig deep enough to tell which modules in particular are missing, but for example:

iptables canary mangle/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 3: iptables v1.8.2 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
May 28 08:04:49 u3 k3s[6076]: Perhaps iptables or your kernel needs to be upgraded.

I tried to build a kernel on my own but currently don't have time to dive into it. The readme at https://github.com/hexdump0815/linux-mainline-and-mali-generic-stable-kernel/blob/master/readme.exy is imho very complex. I tried using https://github.com/rodolfoap/kernel-odroid-u3 because it has an easy build.sh but it did not work with recent kernels. I will try it again though, using the network settings from the raspberry pi kernels (because k8s works great there).

It would also be nice to have wireguard as a module in the kernel. 

this would make the u3 a valuable member for a kubernetes cluster with these changes.

**Comment by hexdump0815** [comment]
hi @lotherk 

as everyone has its own wishes regarding kernel options i would prefer to encourage everyone to just build their own kernels with the options needed - i try to provide enough options to support the hardware included, some generic hardware and basic docker support ... compiling the kernel following the readme.exy should not be that complicated once one is getting used to it: just make sure the you have the dir structure mentioned on top of the file and then you can just copy and paste all the lines below until the tar of the resulting kernel step by step

good luck and best wishes - hexdump

**Comment by lotherk** [comment]
hi @hexdump0815,

Yes, that makes sense. I've made my own kernel now and the u3 is running well as a k3s master.

**Comment by hexdump0815** [comment]
i'm happy to hear that :)
